Add custom domain guide for svelte-cloudinary configuration #143
cloudinary-community/svelte-cloudinary pull request #155
Opened 2024-10-04 22:32 UTC by error9098x

# Description

Added a guide for configuring a custom domain with svelte-cloudinary, including steps for setting up a private CDN and secure distribution. No additional dependencies required.

## Issue Ticket Number

Fixes #143

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Fix or improve the documentation
- [ ] This change requires a documentation update

# Checklist

- [x] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [x] I have created an [issue](https://github.com/cloudinary-community/svelte-cloudinary/issues) ticket for this PR
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/cloudinary-community/svelte-cloudinary/pulls) for the same update/change?
- [x] I have performed a self-review of my own code
- [x] I have run tests locally to ensure they all pass
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes needed to the documentation

2024-10-06 01:57 UTC, ghostdevv requested changes
Just a couple changes, then it's all good! Thank you

2024-10-06 01:57 UTC, ghostdevv commented on packages/docs/src/content/docs/guides/custom-domain.mdx
> +:::
```suggestion
Enhance the delivery of your media assets by integrating svelte-cloudinary with a [private CDN and/or custom domain](https://cloudinary.com/documentation/advanced_url_delivery_options#private_cdns_and_custom_delivery_hostnames_cnames).

:::note
**Private CDN** and **Custom Domain** features are available exclusively on [Cloudinary's Advanced plan](https://cloudinary.com/pricing).
:::
```

2024-10-06 01:57 UTC, ghostdevv commented on packages/docs/src/content/docs/guides/custom-domain.mdx
> +Replace `your_cloud_name` with your actual Cloudinary cloud name and `your-custom-domain.com` with your custom domain.
```suggestion
```bash
VITE_CLOUDINARY_CLOUD_NAME="your_cloud_name"
VITE_CLOUDINARY_PRIVATE_CDN="true"
VITE_CLOUDINARY_SECURE_DISTRIBUTION="your-custom-domain.com"
```

Replace `your_cloud_name` with your actual [Cloudinary cloud name](https://cloudinary.com/documentation/finding_your_credentials_tutorial) and `your-custom-domain.com` with your custom domain. Read more about [configuring svelte-cloudinary here](https://svelte.cloudinary.dev/config).
```

2024-10-06 01:57 UTC, ghostdevv commented on packages/docs/src/content/docs/guides/custom-domain.mdx
> +```
```suggestion
```

These steps aren't needed, since we're using enviornment variables!

2024-10-06 01:57 UTC, ghostdevv commented on packages/docs/src/content/docs/guides/custom-domain.mdx
> +  src="sample.jpg"
```suggestion
  src="<Your Public ID>"
```

2024-10-06 18:04 UTC, error9098x commented
Hi @ghostdevv, I have added the suggested changes :)

2024-10-06 19:30 UTC, ghostdevv requested changes

2024-10-06 19:30 UTC, ghostdevv commented on packages/docs/src/content/docs/guides/custom-domain.mdx
> +Replace your_cloud_name with your actual Cloudinary cloud name and your-custom-domain.com with your custom domain. Read more about configuring svelte-cloudinary here.
```suggestion
Replace your_cloud_name with your actual Cloudinary cloud name and your-custom-domain.com with your custom domain. Read more about [configuring svelte-cloudinary here](https://svelte.cloudinary.dev/config).
```

2024-10-06 19:30 UTC, ghostdevv commented on packages/docs/src/content/docs/guides/custom-domain.mdx
> +```
```suggestion
```

2024-10-06 19:32 UTC, ghostdevv approved these changes
perfect, ty!

2024-10-06 19:33 UTC, merged

2024-10-06 19:48 UTC, error9098x commented
@ghostdevv thanks, can you add hacktoberfest tag in this PR ? this is my first PR during HF :)

2024-10-06 21:16 UTC, ghostdevv commented
@error9098x it's on the repo don't worry! let me know if it doesn't show up on your hacktoberfest account in a couple days :pray:

2024-10-06 21:19 UTC, error9098x commented
> @error9098x it's on the repo don't worry! let me know if it doesn't show up on your hacktoberfest account in a couple days 🙏

I just checked, it appeared! 😄 🎊

2024-10-07 15:06 UTC, colbyfayock commented
@error9098x thanks for your contribution. This PR is eligible for free Cloudinary Hacktoberfest swag. Please send me an email to hacktoberfest@cloudinary.com with your name, GitHub username, a link to this PR. Happy Hacktoberfest!